### ISSUE TITLE
Failed to find style 'ecoGalleryStyle' in current theme

### ISSUE THREAD

**Issue by mnowrot** [falnatsheh/EcoGallery#4]
Dear Feras,

after introducing the EcoGallery to my project, the following information/warning started to be shown in the GraphicalLayout of the fragment in which I'm using your library:
```
Missing styles. Is the correct theme chosen for this layout?
Use the Theme combo box above the layout to choose a different layout,
or fix the theme style references.

Failed to find style 'ecoGalleryStyle' in current theme
```
Is there something additional I should do to make this warning disappear?

Best Regards,

Marcin

**Comment by hastoukopsaro** [comment]
For future users... if any :P

Just add an empty style in your `AppTheme` in `styles.xml` like so

```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="ecoGalleryStyle">@style/ecoGalleryStyle</item>
</style>

<style name="ecoGalleryStyle"> </style>
```

**Comment by falnatsheh** [comment]
Thanks @hastoukopsaro I'll make a note in the README about this.

**Comment by falnatsheh** [comment]
Link for the note: https://github.com/falnatsheh/EcoGallery/blob/master/README.md

**Comment by hastoukopsaro** [comment]
Glad to be of service... Your lib saved me some hours of coding... there are some stuff that viewpager just can't handle in such a simple manner. Cheers!
